name: Build

on:
    push:

jobs:
    build:
        strategy:
            matrix:
                node: [ 20 ]
                os:
                    # we just build web typically
                    - ubuntu-latest
                    # - windows-latest
                    # - macos-latest
        name: ${{ matrix.os }} Node ${{ matrix.node}}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: 'mac: fixup python'
              if: runner.os == 'macOS'
              run: brew install python-setuptools
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node }}
            - name: Cache npm repository
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: npm-${{ runner.os }}-build-${{ hashFiles('**/package.json') }}
                restore-keys: |
                    npm-${{ runner.os }}-build-
                    npm-
            - run: |
                npm ci
                cd browser-app
                npm run bundle
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # lint
            # test
