name: Build

on:
    push:

jobs:
    build:
        strategy:
            matrix:
                node: [ 20 ]
                os:
                    - ubuntu-latest
                    # - windows-latest
                    # - macos-latest
        name: ${{ matrix.os }} Node ${{ matrix.node}}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node }}
            - name: Cache npm repository
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ runner.os }}-lint-${{ hashFiles('**/package.json') }}
                restore-keys: |
                    ${{ runner.os }}-npm-
                    npm-
            - run: |
                npm ci
                npm run build:browser
                #npm run build:electron
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # lint
            # test
