name: Build Electron

on:
    workflow_dispatch:
    release:
    push:
        paths:
            - 'electron-app/**'
            - '.github/workflows/electron.yml'

jobs:
    build:
        strategy:
            matrix:
                node: [ 20 ]
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
        name: Electron ${{ matrix.os }} Node ${{ matrix.node}}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node }}
            - name: 'mac: fixup python'
              if: runner.os == 'macOS'
              run: brew install python-setuptools
            - name: Cache npm repository
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: npm-${{ runner.os }}-electron-${{ hashFiles('**/package.json') }}
                restore-keys: |
                    npm-${{ runner.os }}-electron-
                    npm-
            - run: |
                npm ci
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: build electron
              run: |
                cd electron-app
                npm run bundle
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: package electron
              if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
              run: |
                cd electron-app
                npm run package
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # - TODO: lint
            # - TODO: test
            - name: Upload electron artifact
              if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
              uses: actions/upload-artifact@v4
              with:
                name: electron-app-${{ runner.os }}
                path: electron-app/dist/keyman*
