name: Build Electron

on:
    workflow_dispatch:
    release:
    push:
        paths:
            - 'electron-app/**'

jobs:
    build:
        strategy:
            matrix:
                node: [ 20 ]
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
        name: Electron ${{ matrix.os }} Node ${{ matrix.node}}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node }}
            - name: Cache npm repository
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: npm-${{ runner.os }}-electron-${{ hashFiles('**/package.json') }}
                restore-keys: |
                    npm-${{ runner.os }}-electron-
                    npm-
            - run: |
                npm ci
                # workaround for strange build issue #2
                ( mkdir -pv node_modules/@theia/application-manager/node_modules/.bin/ && ln -sfv ../../../../.bin/webpack ./node_modules/@theia/application-manager/node_modules/.bin/webpack)
                # npm run build:browser
                npm run build:electron
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # lint
            # test
            # TODO: package result!
